In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

# studentVle

In [28]:
studvle = pd.read_csv('./data/studentVle.csv')
studvle

         code_module code_presentation  id_student  id_site  date  sum_click
0                AAA             2013J       28400   546652   -10          4
1                AAA             2013J       28400   546652   -10          1
2                AAA             2013J       28400   546652   -10          1
3                AAA             2013J       28400   546614   -10         11
4                AAA             2013J       28400   546714   -10          1
...              ...               ...         ...      ...   ...        ...
10655275         GGG             2014J      675811   896943   269          3
10655276         GGG             2014J      675578   896943   269          1
10655277         GGG             2014J      654064   896943   269          3
10655278         GGG             2014J      654064   896939   269          1
10655279         GGG             2014J      654064   896939   269          1

[10655280 rows x 6 columns]

# vle

In [29]:
vle = pd.read_csv('./data/vle.csv')
vle

      id_site code_module code_presentation activity_type  week_from  week_to
0      546943         AAA             2013J      resource        NaN      NaN
1      546712         AAA             2013J     oucontent        NaN      NaN
2      546998         AAA             2013J      resource        NaN      NaN
3      546888         AAA             2013J           url        NaN      NaN
4      547035         AAA             2013J      resource        NaN      NaN
...       ...         ...               ...           ...        ...      ...
6359   897063         GGG             2014J      resource        NaN      NaN
6360   897109         GGG             2014J      resource        NaN      NaN
6361   896965         GGG             2014J     oucontent        NaN      NaN
6362   897060         GGG             2014J      resource        NaN      NaN
6363   897100         GGG             2014J      resource        NaN      NaN

[6364 rows x 6 columns]

In [30]:
site_activity = {}
for ids, ac in zip(vle['id_site'], vle['activity_type']):
    site_activity[ids] = ac

In [31]:
# map the site id by actiity_type
studvle['id_site'] = studvle['id_site'].map(site_activity)
studvle

         code_module code_presentation  id_student    id_site  date  sum_click
0                AAA             2013J       28400    forumng   -10          4
1                AAA             2013J       28400    forumng   -10          1
2                AAA             2013J       28400    forumng   -10          1
3                AAA             2013J       28400   homepage   -10         11
4                AAA             2013J       28400  oucontent   -10          1
...              ...               ...         ...        ...   ...        ...
10655275         GGG             2014J      675811   homepage   269          3
10655276         GGG             2014J      675578   homepage   269          1
10655277         GGG             2014J      654064   homepage   269          3
10655278         GGG             2014J      654064    forumng   269          1
10655279         GGG             2014J      654064    forumng   269          1

[10655280 rows x 6 columns]

In [32]:
group_result = studvle.groupby(['code_module', 'code_presentation', 'id_student', 'id_site'])['id_site', 'sum_click'].agg({'id_site':'count', 'sum_click':'sum'})
group_result

                                                    id_site  sum_click
code_module code_presentation id_student id_site
AAA         2013J             11391      forumng         52        193
                                         homepage        40        138
                                         oucontent       78        553
                                         resource        11         13
                                         subpage         11         32
...                                                     ...        ...
GGG         2014J             2684003    homepage        34        120
                                         oucontent       38        265
                                         quiz            27         60
                                         resource        10         33
                                         subpage         20         27

[240357 rows x 2 columns]

# lets create columns based on activity type and click sum

In [33]:
cols_open = []
cols_click = []
for name in vle['activity_type'].value_counts().index:
    cols_open.append(name)
    cols_click.append(name+'_click')

In [34]:
all_cols = cols_open+cols_click
all_cols

['resource',
 'subpage',
 'oucontent',
 'url',
 'forumng',
 'quiz',
 'page',
 'oucollaborate',
 'questionnaire',
 'ouwiki',
 'dataplus',
 'externalquiz',
 'homepage',
 'glossary',
 'ouelluminate',
 'dualpane',
 'repeatactivity',
 'htmlactivity',
 'sharedsubpage',
 'folder',
 'resource_click',
 'subpage_click',
 'oucontent_click',
 'url_click',
 'forumng_click',
 'quiz_click',
 'page_click',
 'oucollaborate_click',
 'questionnaire_click',
 'ouwiki_click',
 'dataplus_click',
 'externalquiz_click',
 'homepage_click',
 'glossary_click',
 'ouelluminate_click',
 'dualpane_click',
 'repeatactivity_click',
 'htmlactivity_click',
 'sharedsubpage_click',
 'folder_click']

In [35]:
studinfo = pd.read_csv('./data/studentInfo.csv')

dd = pd.DataFrame(np.zeros((len(studinfo), 40)), columns=all_cols)
newdf = pd.concat([studinfo[['code_module', 'code_presentation','id_student']], dd], axis=1)
newdf

,code_module,code_presentation,id_student,resource,subpage,oucontent,url,forumng,quiz,page,...,dataplus_click,externalquiz_click,homepage_click,glossary_click,ouelluminate_click,dualpane_click,repeatactivity_click,htmlactivity_click,sharedsubpage_click,folder_click
0,AAA,2013J,11391,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AAA,2013J,28400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AAA,2013J,30268,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AAA,2013J,31604,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AAA,2013J,32885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32589,GGG,2014J,2645731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32590,GGG,2014J,2648187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32591,GGG,2014J,2679821,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32592,GGG,2014J,2684003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
i=0
for row in newdf.iterrows():
    m = row[1][0]
    t = row[1][1]
    s = row[1][2]
    try:
        ss = group_result.loc[(m, t, s, ), ].T
        cols = list(ss.loc['id_site'].index)
        vals = list(ss.loc['id_site'].values)
        newdf.loc[row[0], cols] = vals
        cols = [col+'_click' for col in cols]
        vals = list(ss.loc['sum_click'].values)
        newdf.loc[row[0], cols] = vals
    except:
        i+=1
print('No record match: ', i)

No record match:  3365

In [37]:
newdf

,code_module,code_presentation,id_student,resource,subpage,oucontent,url,forumng,quiz,page,...,dataplus_click,externalquiz_click,homepage_click,glossary_click,ouelluminate_click,dualpane_click,repeatactivity_click,htmlactivity_click,sharedsubpage_click,folder_click
0,AAA,2013J,11391,11.0,11.0,78.0,4.0,52.0,0.0,0.0,...,0.0,0.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AAA,2013J,28400,9.0,42.0,106.0,27.0,163.0,0.0,0.0,...,10.0,0.0,324.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AAA,2013J,30268,4.0,12.0,14.0,4.0,30.0,0.0,0.0,...,0.0,0.0,59.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AAA,2013J,31604,13.0,83.0,196.0,51.0,197.0,0.0,0.0,...,2.0,0.0,432.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AAA,2013J,32885,23.0,53.0,115.0,13.0,77.0,0.0,0.0,...,0.0,0.0,204.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,4.0,6.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32589,GGG,2014J,2645731,67.0,20.0,61.0,0.0,14.0,38.0,0.0,...,0.0,0.0,167.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
32590,GGG,2014J,2648187,14.0,14.0,21.0,0.0,0.0,36.0,0.0,...,0.0,0.0,63.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
32591,GGG,2014J,2679821,9.0,6.0,11.0,0.0,17.0,5.0,0.0,...,0.0,0.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32592,GGG,2014J,2684003,10.0,20.0,38.0,0.0,52.0,27.0,0.0,...,0.0,0.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
newdf.to_csv('student_activityType_sumClick.csv', index=False)

In [39]:
merge = pd.merge(studinfo, newdf, on=['code_module', 'code_presentation','id_student'], how='inner')
merge

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,dataplus_click,externalquiz_click,homepage_click,glossary_click,ouelluminate_click,dualpane_click,repeatactivity_click,htmlactivity_click,sharedsubpage_click,folder_click
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,0.0,0.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,10.0,0.0,324.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,...,0.0,0.0,59.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,2.0,0.0,432.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,0.0,0.0,204.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,...,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,...,0.0,0.0,167.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
32590,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,...,0.0,0.0,63.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,...,0.0,0.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32592,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,...,0.0,0.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
merge.query('code_module=="GGG" and code_presentation=="2014J"').groupby('final_result')[cols_open].mean()

,resource,subpage,oucontent,url,forumng,quiz,page,oucollaborate,questionnaire,ouwiki,dataplus,externalquiz,homepage,glossary,ouelluminate,dualpane,repeatactivity,htmlactivity,sharedsubpage,folder
final_result,,,,,,,,,,,,,,,,,,,,
Distinction,28.330709,20.212598,61.133858,0.0,50.543307,38.165354,0.0,0.0,0.0,0.0,0.0,0.0,52.685039,2.543307,0.0,0.0,0.0,0.0,0.0,0.0
Fail,16.530726,8.480447,17.932961,0.0,9.564246,11.620112,0.0,0.0,0.0,0.0,0.0,0.0,16.195531,0.743017,0.0,0.0,0.0,0.0,0.0,0.0
Pass,27.558360,17.820189,51.460568,0.0,33.195584,37.599369,0.0,0.0,0.0,0.0,0.0,0.0,42.675079,1.706625,0.0,0.0,0.0,0.0,0.0,0.0
Withdrawn,8.968254,3.753968,6.428571,0.0,3.341270,1.714286,0.0,0.0,0.0,0.0,0.0,0.0,6.857143,0.126984,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
merge.groupby('final_result')[cols_open].mean()

,resource,subpage,oucontent,url,forumng,quiz,page,oucollaborate,questionnaire,ouwiki,dataplus,externalquiz,homepage,glossary,ouelluminate,dualpane,repeatactivity,htmlactivity,sharedsubpage,folder
final_result,,,,,,,,,,,,,,,,,,,,
Distinction,45.097553,110.358466,121.293320,24.869378,179.631944,65.177579,2.980159,3.960979,4.071759,12.590939,1.338955,2.219907,106.071759,1.095899,0.811508,0.714616,0.000000,0.373347,0.005952,0.215939
Fail,17.398894,38.416336,32.309274,7.443137,35.572887,15.884572,1.039563,0.970930,0.471781,2.573454,0.067924,1.038571,31.601390,0.286727,0.593023,0.148185,0.000425,0.135281,0.003829,0.056580
Pass,37.237602,92.596796,98.148936,19.285737,114.298520,43.660060,2.042068,3.375131,2.199013,8.800097,0.714020,2.558531,83.571475,0.864655,1.073457,0.509020,0.000162,0.258474,0.006391,0.291805
Withdrawn,9.237790,19.759059,15.353190,4.099153,19.845018,6.476566,0.587239,0.516739,0.205100,1.296180,0.014967,0.516640,15.614907,0.138933,0.241729,0.064494,0.000098,0.153308,0.002363,0.001871

In [52]:
merge.groupby('final_result')[cols_click].mean()

,resource_click,subpage_click,oucontent_click,url_click,forumng_click,quiz_click,page_click,oucollaborate_click,questionnaire_click,ouwiki_click,dataplus_click,externalquiz_click,homepage_click,glossary_click,ouelluminate_click,dualpane_click,repeatactivity_click,htmlactivity_click,sharedsubpage_click,folder_click
final_result,,,,,,,,,,,,,,,,,,,,
Distinction,59.246693,192.460317,720.124008,34.959987,625.313823,463.281085,3.810847,6.379299,5.648479,71.484458,4.849868,2.642857,466.729497,6.209325,1.422288,1.438492,0.000000,0.510582,0.006283,0.240741
Fail,23.808140,68.408395,174.465258,10.339762,113.043534,124.803744,1.458593,1.640811,0.724759,11.157402,0.238939,1.353659,117.642371,1.212422,0.973341,0.327567,0.000425,0.178389,0.004396,0.070760
Pass,51.484508,161.384354,568.710299,26.889572,373.609336,340.552706,2.694685,5.605614,3.176604,44.206132,2.481676,3.227571,329.722272,4.393577,1.949680,1.024189,0.000162,0.351428,0.007038,0.337351
Withdrawn,12.472922,34.688263,75.717901,5.482966,65.682651,48.305435,0.838125,0.868551,0.325522,5.241138,0.043423,0.675266,62.264967,0.622883,0.370520,0.137456,0.000394,0.206085,0.003348,0.002265